---
all:
  children:
    test:
      hosts:
        lightwell-test-01:
          ansible_host: test.lightwell-demo.example.com
    prod:
      hosts:
        lightwell-prod-01:
          ansible_host: prod.lightwell-demo.example.com
