---
app_container_name: "lightwell-patch-demo-app{{ '-dev' if app_environment == 'dev' else '' }}"
app_host_port: "{{ 8080 if app_environment == 'dev' else 8081 }}"
app_previous_image_file: "/opt/lightwell-demo/{{ app_environment }}/previous_image.txt"
quadlet_dir: /etc/containers/systemd
app_service_name: "{{ app_container_name }}"
